### ISSUE TITLE
Scripts on C#

### ISSUE THREAD

**Issue by EugenePat** [lench4991/LenchScripterMod#2]
Hello, can you add C# script support for LenchScripterMod? I think this project can help do it: https://github.com/oleg-shilo/cs-script

**Comment by lench4991** [comment]
I'm centering this mod around Python so I don't find it very elegant to support multiple different languages with it. I want to avoid complicating the UI and the script resolving mechanisms even more. However, you are welcome to fork it and implement a separate C# mod yourself; I believe the changes would be fairly minimal. I would definitely try to contribute.

I think there's a built in solution to compiling C# without requiring any additional libraries though.
Quick Google search returns [this](http://stackoverflow.com/questions/826398/is-it-possible-to-dynamically-compile-and-execute-c-sharp-code-fragments) and [this](http://stackoverflow.com/questions/4181668/execute-c-sharp-code-at-runtime-from-code-file).

**Comment by EugenePat** [comment]
Thanks, Lench, I'll try to do
