### ISSUE TITLE
Imported modules are not reloaded

### ISSUE THREAD

**Issue by pjwerneck** [lench4991/LenchScripterMod#6]
Modules present in the scripts folder that are imported by an script file are not being reloaded between executions. This is expected behavior from IronPython since it imports modules only once per session. 

One workaround is to add a `reload(modulename)` right after the import, but it would be more user-friendly to automatically reload all modules when building the python environment.

**Comment by lench4991** [comment]
Added a call to `sys.modules.clear()` at the start of environment creation. Unsure if this is the best solution, but it appears to be working with multiple `PythonEnvironment` instances.

[Link to relevant commit.](https://github.com/lench4991/LenchScripterMod/commit/0c3959623166ffa3745e1711de8e6e8f9bacfc56)

[Download v2.2.1.1 hotfix - LenchScripterMod.zip](https://github.com/lench4991/LenchScripterMod/files/852725/LenchScripterMod.zip)

`

**Comment by pjwerneck** [comment]
It's a bit drastic but it's working perfectly. Thanks.
